"""Added registration date for 'user'

Revision ID: 1c12ebb93352
Revises: 321ea0f5b77a
Create Date: 2024-11-05 16:07:45.227201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c12ebb93352'
down_revision: Union[str, None] = '321ea0f5b77a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('registration_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'registration_date')
    # ### end Alembic commands ###
