"""Added matches update for User

Revision ID: c01ae9548c2c
Revises: 6b74a042ff12
Create Date: 2024-11-06 01:18:01.066454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c01ae9548c2c'
down_revision: Union[str, None] = '6b74a042ff12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('matches_update', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'matches_update')
    # ### end Alembic commands ###
